# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\frenc\Desktop\CaeserCipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 480)
        MainWindow.setMinimumSize(QtCore.QSize(480, 480))
        MainWindow.setMaximumSize(QtCore.QSize(480, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(30, 20, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.input_text_data = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text_data.setGeometry(QtCore.QRect(30, 110, 431, 111))
        self.input_text_data.setObjectName("input_text_data")
        self.label_input_header = QtWidgets.QLabel(self.centralwidget)
        self.label_input_header.setGeometry(QtCore.QRect(20, 70, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_input_header.setFont(font)
        self.label_input_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_header.setObjectName("label_input_header")
        self.label_input_key_header = QtWidgets.QLabel(self.centralwidget)
        self.label_input_key_header.setGeometry(QtCore.QRect(10, 240, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_input_key_header.setFont(font)
        self.label_input_key_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_key_header.setObjectName("label_input_key_header")
        self.input_line_key = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line_key.setGeometry(QtCore.QRect(30, 280, 431, 21))
        self.input_line_key.setObjectName("input_line_key")
        self.button_encrypt_append = QtWidgets.QPushButton(self.centralwidget)
        self.button_encrypt_append.setGeometry(QtCore.QRect(44, 320, 121, 41))
        self.button_encrypt_append.setObjectName("button_encrypt_append")
        self.button_reset_file = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset_file.setGeometry(QtCore.QRect(310, 320, 121, 41))
        self.button_reset_file.setObjectName("button_reset_file")
        self.radio_encrypt = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_encrypt.setGeometry(QtCore.QRect(80, 370, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_encrypt.setFont(font)
        self.radio_encrypt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radio_encrypt.setObjectName("radio_encrypt")
        self.radio_decrypt = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_decrypt.setGeometry(QtCore.QRect(310, 370, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_decrypt.setFont(font)
        self.radio_decrypt.setObjectName("radio_decrypt")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(20, 400, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_output.setFont(font)
        self.label_output.setText("")
        self.label_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_output.setObjectName("label_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ceaser Cipher"))
        self.label_title.setText(_translate("MainWindow", "Ceaser Cipher Encryptor"))
        self.label_input_header.setText(_translate("MainWindow", "Enter text to be encrypted:"))
        self.label_input_key_header.setText(_translate("MainWindow", "Enter Cipher Key. (Any num in 1-26):"))
        self.button_encrypt_append.setText(_translate("MainWindow", "Encrypt and Append"))
        self.button_reset_file.setText(_translate("MainWindow", "Reset File"))
        self.radio_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.radio_decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
